In [229]:
import pandas as pd

df1 = pd.read_csv("/home/ash/Desktop/kairos/code/brain/src/parsed/data_feeds_20240705_20240705_IEXTP1_DEEP1.0_prl.csv")

df1.head(20)

,Packet Capture Time,Send Time,Buy_Ask Flag,Exchange Timestamp,Tick Type,Symbol,Price,Size,Record Type,Event Flag
0,1720180800247255040,1720180800247207355,0,1720180800233199068,PRL,NVDA,98.00,10,R,1
1,1720180812922964992,1720180812922949078,1,1720180812922789628,PRL,AAPL,222.22,20,R,1
2,1720180818332749056,1720180818332736199,0,1720180818332587823,PRL,NVDA,126.76,1,R,1
3,1720180818523296000,1720180818523279525,1,1720180818523147667,PRL,NVDA,130.00,1000,R,1
4,1720180822372899072,1720180822372879042,0,1720180822372773365,PRL,NVDA,119.00,12,R,1
5,1720180826876144896,1720180826876114162,1,1720180826876017816,PRL,NVDA,145.00,1,R,1
6,1720180826909038080,1720180826909022198,1,1720180826908942948,PRL,NVDA,140.92,100,R,1
7,1720180827525515008,1720180827525502900,1,1720180827525407144,PRL,NVDA,147.00,1,R,1
8,1720180830410338048,1720180830410312198,0,1720180830410227402,PRL,NVDA,96.20,100,R,1
9,1720181071182061056,1720181071182049033,0,1720181071181975136,PRL,SPY,549.69,1000,R,1
10,1720181071190076928,1720181071190064373,1,1720181071189996061,PRL,SPY,553.41,1000,R,1
11,1720181071281101056,1720181071281091706,0,1720181071281026726,PRL,SPY,549.84,1000,R,1
12,1720181071287545088,1720181071287368752,1,1720181071287304656,PRL,SPY,553.26,1000,R,1
13,1720181071380402944,1720181071380391357,0,1720181071380330003,PRL,SPY,550.13,1000,R,1
14,1720181071384537088,1720181071384469714,1,1720181071384407816,PRL,SPY,552.97,1000,R,1
15,1720181071479823104,1720181071479813058,0,1720181071479750108,PRL,SPY,550.28,1000,R,1
16,1720181071483092992,1720181071483050110,1,1720181071482984075,PRL,SPY,552.82,1000,R,1
17,1720181071579183104,1720181071579173027,0,1720181071579117319,PRL,SPY,550.43,1000,R,1
18,1720181071581839872,1720181071581827441,1,1720181071581766082,PRL,SPY,552.53,1000,R,1
19,1720181071678768896,1720181071678759442,0,1720181071678689301,PRL,SPY,550.72,1000,R,1

In [230]:
df1["Record Type"].unique()
r = df1[(df1["Record Type"] == 'Z') 
        & (df1["Event Flag"] == 1)
    ]
r

,Packet Capture Time,Send Time,Buy_Ask Flag,Exchange Timestamp,Tick Type,Symbol,Price,Size,Record Type,Event Flag
21,1720181072677873920,1720181072677863459,1,1720181072677799580,PRL,SPY,553.41,0,Z,1
22,1720181073077879040,1720181073077867073,0,1720181073077832893,PRL,SPY,549.69,0,Z,1
24,1720181078377684992,1720181078377640960,1,1720181078377593362,PRL,SPY,553.43,0,Z,1
26,1720181102477761024,1720181102477746056,1,1720181102477698540,PRL,SPY,553.42,0,Z,1
29,1720181200955760128,1720181200955746788,0,1720181200955427762,PRL,AAPL,221.66,0,Z,1
...,...,...,...,...,...,...,...,...,...,...
694969,1720213200029011968,1720213200028974088,1,1720213200005677689,PRL,NVDA,130.00,0,Z,1
694970,1720213200029015040,1720213200028985451,1,1720213200005689212,PRL,NVDA,147.00,0,Z,1
694971,1720213200030117888,1720213200030108262,0,1720213200005937091,PRL,NVDA,98.00,0,Z,1
694972,1720213200030287104,1720213200030275566,1,1720213200005949132,PRL,NVDA,145.00,0,Z,1
694973,1720213200030306048,1720213200030290193,0,1720213200005962679,PRL,NVDA,124.90,0,Z,1

In [231]:
df1['Datetime'] = pd.to_datetime(df1["Exchange Timestamp"], unit='ns', utc=True)
df1["Datetime_EST"] = df1["Datetime"].dt.tz_convert("US/Eastern")
df1['Second'] = df1['Datetime_EST'].dt.floor('s')
df1 = df1[df1["Size"] != 0]

In [232]:
print("the number of zeros is :", len(df1) - df1[" Buy_Ask Flag"].sum())
print("the number of ones is :", df1[" Buy_Ask Flag"].sum())
df1.info()

the number of zeros is : 264470
the number of ones is : 200542
<class 'pandas.DataFrame'>
Index: 465012 entries, 0 to 694948
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Packet Capture Time  465012 non-null  int64
 1   Send Time            465012 non-null  int64
 2    Buy_Ask Flag        465012 non-null  int64
 3   Exchange Timestamp   465012 non-null  int64
 4   Tick Type            465012 non-null  str
 5   Symbol               465012 non-null  str
 6   Price                465012 non-null  float64
 7   Size                 465012 non-null  int64
 8   Record Type          465012 non-null  str
 9   Event Flag           465012 non-null  int64
 10  Datetime             465012 non-null  datetime64[ns, UTC]
 11  Datetime_EST         465012 non-null  datetime64[ns, US/Eastern]
 12  Second               465012 non-null  datetime64[ns, US/Eastern]
dtypes: datetime64[ns, US/Eastern](2), datetime64[ns, UTC](1), float64(1), int64(6), str(3)
memory usage: 49.7 MB

In [233]:
ask = df1[df1[" Buy_Ask Flag"] == 1].copy()
ask

,Packet Capture Time,Send Time,Buy_Ask Flag,Exchange Timestamp,Tick Type,Symbol,Price,Size,Record Type,Event Flag,Datetime,Datetime_EST,Second
1,1720180812922964992,1720180812922949078,1,1720180812922789628,PRL,AAPL,222.22,20,R,1,2024-07-05 12:00:12.922789628+00:00,2024-07-05 08:00:12.922789628-04:00,2024-07-05 08:00:12-04:00
3,1720180818523296000,1720180818523279525,1,1720180818523147667,PRL,NVDA,130.00,1000,R,1,2024-07-05 12:00:18.523147667+00:00,2024-07-05 08:00:18.523147667-04:00,2024-07-05 08:00:18-04:00
5,1720180826876144896,1720180826876114162,1,1720180826876017816,PRL,NVDA,145.00,1,R,1,2024-07-05 12:00:26.876017816+00:00,2024-07-05 08:00:26.876017816-04:00,2024-07-05 08:00:26-04:00
6,1720180826909038080,1720180826909022198,1,1720180826908942948,PRL,NVDA,140.92,100,R,1,2024-07-05 12:00:26.908942948+00:00,2024-07-05 08:00:26.908942948-04:00,2024-07-05 08:00:26-04:00
7,1720180827525515008,1720180827525502900,1,1720180827525407144,PRL,NVDA,147.00,1,R,1,2024-07-05 12:00:27.525407144+00:00,2024-07-05 08:00:27.525407144-04:00,2024-07-05 08:00:27-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
694937,1720212846262009088,1720212846261981662,1,1720212846261954455,PRL,SPY,556.12,1000,R,1,2024-07-05 20:54:06.261954455+00:00,2024-07-05 16:54:06.261954455-04:00,2024-07-05 16:54:06-04:00
694939,1720212885146217984,1720212885146183655,1,1720212885146140641,PRL,SPY,556.12,1000,R,1,2024-07-05 20:54:45.146140641+00:00,2024-07-05 16:54:45.146140641-04:00,2024-07-05 16:54:45-04:00
694941,1720213113410459904,1720213113410447959,1,1720213113410392456,PRL,SPY,554.86,1000,R,1,2024-07-05 20:58:33.410392456+00:00,2024-07-05 16:58:33.410392456-04:00,2024-07-05 16:58:33-04:00
694945,1720213122660561920,1720213122660544510,1,1720213122660515280,PRL,SPY,555.93,1000,R,1,2024-07-05 20:58:42.660515280+00:00,2024-07-05 16:58:42.660515280-04:00,2024-07-05 16:58:42-04:00
694948,1720213126467929088,1720213126467907194,1,1720213126467878631,PRL,SPY,555.88,1000,R,1,2024-07-05 20:58:46.467878631+00:00,2024-07-05 16:58:46.467878631-04:00,2024-07-05 16:58:46-04:00

In [234]:
AAPL = ask[ask["Symbol"] == "AAPL"]
AAPL

,Packet Capture Time,Send Time,Buy_Ask Flag,Exchange Timestamp,Tick Type,Symbol,Price,Size,Record Type,Event Flag,Datetime,Datetime_EST,Second
1,1720180812922964992,1720180812922949078,1,1720180812922789628,PRL,AAPL,222.22,20,R,1,2024-07-05 12:00:12.922789628+00:00,2024-07-05 08:00:12.922789628-04:00,2024-07-05 08:00:12-04:00
1722,1720185850643181056,1720185850643166735,1,1720185850643128549,PRL,AAPL,222.48,25,R,1,2024-07-05 13:24:10.643128549+00:00,2024-07-05 09:24:10.643128549-04:00,2024-07-05 09:24:10-04:00
1796,1720185964014060032,1720185964014047959,1,1720185964014002567,PRL,AAPL,221.60,100,R,1,2024-07-05 13:26:04.014002567+00:00,2024-07-05 09:26:04.014002567-04:00,2024-07-05 09:26:04-04:00
2194,1720186200206049024,1720186200206030986,1,1720186200034205137,PRL,AAPL,221.86,200,R,1,2024-07-05 13:30:00.034205137+00:00,2024-07-05 09:30:00.034205137-04:00,2024-07-05 09:30:00-04:00
2198,1720186200270433024,1720186200270417770,1,1720186200044122668,PRL,AAPL,221.80,200,R,1,2024-07-05 13:30:00.044122668+00:00,2024-07-05 09:30:00.044122668-04:00,2024-07-05 09:30:00-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
694526,1720209599906912000,1720209599906752954,1,1720209599906708489,PRL,AAPL,226.31,200,R,1,2024-07-05 19:59:59.906708489+00:00,2024-07-05 15:59:59.906708489-04:00,2024-07-05 15:59:59-04:00
694538,1720209599930800128,1720209599930767497,1,1720209599930721503,PRL,AAPL,226.32,200,R,1,2024-07-05 19:59:59.930721503+00:00,2024-07-05 15:59:59.930721503-04:00,2024-07-05 15:59:59-04:00
694546,1720209599957339904,1720209599957329636,1,1720209599957243844,PRL,AAPL,226.33,300,R,1,2024-07-05 19:59:59.957243844+00:00,2024-07-05 15:59:59.957243844-04:00,2024-07-05 15:59:59-04:00
694548,1720209599957737984,1720209599957725728,1,1720209599957701719,PRL,AAPL,226.33,500,R,1,2024-07-05 19:59:59.957701719+00:00,2024-07-05 15:59:59.957701719-04:00,2024-07-05 15:59:59-04:00
694551,1720209599993789952,1720209599993337336,1,1720209599993313416,PRL,AAPL,226.33,300,R,1,2024-07-05 19:59:59.993313416+00:00,2024-07-05 15:59:59.993313416-04:00,2024-07-05 15:59:59-04:00

In [235]:
bid = df1[df1[" Buy_Ask Flag"] == 0].copy()
bid

,Packet Capture Time,Send Time,Buy_Ask Flag,Exchange Timestamp,Tick Type,Symbol,Price,Size,Record Type,Event Flag,Datetime,Datetime_EST,Second
0,1720180800247255040,1720180800247207355,0,1720180800233199068,PRL,NVDA,98.00,10,R,1,2024-07-05 12:00:00.233199068+00:00,2024-07-05 08:00:00.233199068-04:00,2024-07-05 08:00:00-04:00
2,1720180818332749056,1720180818332736199,0,1720180818332587823,PRL,NVDA,126.76,1,R,1,2024-07-05 12:00:18.332587823+00:00,2024-07-05 08:00:18.332587823-04:00,2024-07-05 08:00:18-04:00
4,1720180822372899072,1720180822372879042,0,1720180822372773365,PRL,NVDA,119.00,12,R,1,2024-07-05 12:00:22.372773365+00:00,2024-07-05 08:00:22.372773365-04:00,2024-07-05 08:00:22-04:00
8,1720180830410338048,1720180830410312198,0,1720180830410227402,PRL,NVDA,96.20,100,R,1,2024-07-05 12:00:30.410227402+00:00,2024-07-05 08:00:30.410227402-04:00,2024-07-05 08:00:30-04:00
9,1720181071182061056,1720181071182049033,0,1720181071181975136,PRL,SPY,549.69,1000,R,1,2024-07-05 12:04:31.181975136+00:00,2024-07-05 08:04:31.181975136-04:00,2024-07-05 08:04:31-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
694923,1720212704179358976,1720212704179347951,0,1720212704179303927,PRL,SPY,553.13,1000,R,1,2024-07-05 20:51:44.179303927+00:00,2024-07-05 16:51:44.179303927-04:00,2024-07-05 16:51:44-04:00
694924,1720212704279281920,1720212704279271971,0,1720212704279239016,PRL,SPY,553.28,1000,R,1,2024-07-05 20:51:44.279239016+00:00,2024-07-05 16:51:44.279239016-04:00,2024-07-05 16:51:44-04:00
694931,1720212751224875008,1720212751224863955,0,1720212751224801174,PRL,SPY,553.43,1000,R,1,2024-07-05 20:52:31.224801174+00:00,2024-07-05 16:52:31.224801174-04:00,2024-07-05 16:52:31-04:00
694942,1720213120205260032,1720213120205238616,0,1720213120205196497,PRL,SPY,552.24,1000,R,1,2024-07-05 20:58:40.205196497+00:00,2024-07-05 16:58:40.205196497-04:00,2024-07-05 16:58:40-04:00
694946,1720213122760701952,1720213122760692620,0,1720213122760665868,PRL,SPY,552.23,1000,R,1,2024-07-05 20:58:42.760665868+00:00,2024-07-05 16:58:42.760665868-04:00,2024-07-05 16:58:42-04:00

In [236]:
df1["Event Flag"].unique()

array([1, 0])

In [237]:
bid["Price"].mean() - ask["Price"].mean()

np.float64(-56.04950918155885)

In [238]:
df1["Tick Type"].unique()

<StringArray>
['PRL']
Length: 1, dtype: str

In [239]:
r = df1[df1["Record Type"] == 'Z']
r

Empty DataFrame
Columns: [Packet Capture Time, Send Time,  Buy_Ask Flag, Exchange Timestamp, Tick Type, Symbol, Price, Size, Record Type, Event Flag, Datetime, Datetime_EST, Second]
Index: []

In [240]:
(df1.loc[len(df1) - 1,"Datetime"] - df1.loc[0,"Datetime"])

Timedelta('0 days 05:24:08.458812284')

In [245]:
df = pd.read_csv("/home/ash/Desktop/kairos/code/brain/src/parsed/data_feeds_20240705_20240705_IEXTP1_DEEP1.0_prl.csv")

df = df[df["Record Type"] == 'R']
df = df[df["Event Flag"] == 1]
df = df[df["Size"] != 0]
df.drop(columns =["Event Flag","Record Type","Packet Capture Time","Send Time","Tick Type"],inplace=True)
AAPL_df = df[df["Symbol"] == "AAPL"]
AAPL_df.drop(columns=["Symbol"],inplace=True)
NVDA_df = df[df["Symbol"] == "NVDA"]
NVDA_df.drop(columns=["Symbol"],inplace=True)
SPY_df = df[df["Symbol"] == "SPY"]
SPY_df.drop(columns=["Symbol"],inplace=True)
SPY_df

         Buy_Ask Flag   Exchange Timestamp   Price  Size
9                   0  1720181071181975136  549.69  1000
10                  1  1720181071189996061  553.41  1000
11                  0  1720181071281026726  549.84  1000
12                  1  1720181071287304656  553.26  1000
13                  0  1720181071380330003  550.13  1000
...               ...                  ...     ...   ...
694941              1  1720213113410392456  554.86  1000
694942              0  1720213120205196497  552.24  1000
694945              1  1720213122660515280  555.93  1000
694946              0  1720213122760665868  552.23  1000
694948              1  1720213126467878631  555.88  1000

[215447 rows x 4 columns]

In [5]:
import torch
import numpy as np

# Load just one day of your generated labels
Y = torch.load("/home/ash/Desktop/kairos/code/brain/data/AAPL/AAPL_2024-07-05_Y.pt") 

# Flatten and look at the actual category counts
unique, counts = np.unique(Y.numpy(), return_counts=True)
print("Label Distribution:", dict(zip(unique, counts)))

Label Distribution: {np.int64(0): np.int64(88467)}